export interface ApplicationDBO {
  '" (Prefix)"': string;
  " (First name)": string;
  " (Middle)": string;
  " (Suffix)": string;
  " (Surname)": string;
  "Added value of the FFN Award": string;
  "Additional information": string;
  "Candidate's achievements": string;
  "Conservation vision": string;
  "Country of work": string;
  "Date of birth": string;
  "Email address (Enter Email)": string;
  "Employment record": string;
  "English proficiency": string;
  "Entry Date": string;
  "Entry Id": string;
  "Focal species": string;
  "Formal education": string;
  "Former FFN Award applications": string;
  Gender: string;
  "How did you hear about Future For Nature?": string;
  Nationality: string;
  "Native language": string;
  "Organisation referee 1": string;
  "Organisation referee 2": string;
  "Other awards": string;
  "Position referee 1": string;
  "Position referee 2": string;
  "Postal address (Address Line 2)": string;
  "Postal address (City)": string;
  "Postal address (Country)": string;
  "Postal address (State / Province)": string;
  "Postal address (Street Address)": string;
  "Postal address (ZIP / Postal Code)": string;
  "Referee 1 (First name)": string;
  "Referee 1 (Middle)": string;
  "Referee 1 (Prefix)": string;
  "Referee 1 (Suffix)": string;
  "Referee 1 (Surname)": string;
  "Referee 2 (First name)": string;
  "Referee 2 (Middle)": string;
  "Referee 2 (Prefix)": string;
  "Referee 2 (Suffix)": string;
  "Referee 2 (Surname)": string;
  "Reference statement referee 1": string;
  "Reference statement referee 2": string;
  "Telephone number": string;
}
